# Generated by Django 3.2.6 on 2021-09-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20210828_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('patient', models.ManyToManyField(related_name='physical_activities', to='accounts.Patient')),
            ],
            options={
                'db_table': 'physical_activities',
            },
        ),
        migrations.CreateModel(
            name='HarmfulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('patient', models.ManyToManyField(related_name='harmful_habits', to='accounts.Patient')),
            ],
            options={
                'db_table': 'harmful_habits',
            },
        ),
    ]
