# Generated by Django 3.2.6 on 2021-08-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_patients_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='doi',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
