# Generated by Django 3.2.6 on 2021-08-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210824_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
