# Generated by Django 3.2.6 on 2021-08-29 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210826_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
