# Generated by Django 3.2.6 on 2021-09-20 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patientlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
