# Generated by Django 3.2.6 on 2021-09-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_patientlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
