# Generated by Django 3.2.6 on 2021-11-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_privacytermsaccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacytermsaccept',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
