# Generated by Django 3.2.6 on 2021-11-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_privacytermsaccept_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacytermsaccept',
            name='patient',
        ),
        migrations.AddField(
            model_name='privacytermsaccept',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
