# Generated by Django 3.2.6 on 2021-09-12 04:12

from diseases.utils.seed import create_data_illness
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data_illness)
    ]
