# Generated by Django 3.2.6 on 2021-09-12 17:38

from diseases.utils.seed import create_data_illness
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_auto_20210911_2312'),
    ]

    operations = [
    ]
