# Generated by Django 3.2.6 on 2021-09-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_patientlog_date'),
        ('diseases', '0003_auto_20210912_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('carbohydrate_kcal', models.FloatField()),
                ('fat_kcal', models.FloatField()),
                ('protein_kcal', models.FloatField()),
                ('carbohydrate_grams', models.FloatField()),
                ('fat_grams', models.FloatField()),
                ('protein_grams', models.FloatField()),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='PersonalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'personal_treatments',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='PersonalTreatmentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('personal_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.personaltreatment')),
            ],
            options={
                'db_table': 'personal_treatment_traces',
            },
        ),
        migrations.AddField(
            model_name='personaltreatment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.treatment'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.treatment')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='MealSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('BREAKFAST1', 'Breakfast1'), ('BREAKFAST2', 'Breakfast2'), ('SNACK', 'Snack'), ('LUNCH1', 'Lunch1'), ('LUNCH2', 'Lunch2'), ('LUNCH3', 'Lunch3'), ('DINNER1', 'Dinner1'), ('DINNER2', 'Dinner2')], max_length=50)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.meal')),
                ('menus', models.ManyToManyField(related_name='meal_schedules', to='diets.Menu')),
            ],
            options={
                'db_table': 'meal_schedules',
            },
        ),
        migrations.CreateModel(
            name='BaseTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_old', models.CharField(max_length=4)),
                ('genre', models.BooleanField()),
                ('bmi', models.FloatField()),
                ('tmb', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('illness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diseases.illness')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.treatment')),
            ],
            options={
                'db_table': 'base_treatments',
            },
        ),
    ]
