# Generated by Django 3.2.6 on 2021-08-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20210828_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hour', models.TimeField()),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('progress', models.BooleanField(default=True)),
                ('carbohydrate', models.FloatField()),
                ('fat', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
            ],
            options={
                'db_table': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.treatment')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('carbohydrate', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('recipe', models.TextField(null=True)),
                ('menus', models.ManyToManyField(related_name='meals', to='diets.Menu')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diets.schedule')),
            ],
            options={
                'db_table': 'meals',
            },
        ),
    ]
