# Generated by Django 3.2.6 on 2021-09-26 18:50

from django.db import migrations

from diets.utils.seed import create_meals_data, create_treatments, create_base_treatments, create_menus_data, \
    create_meal_schedule


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_meals_data),
        migrations.RunPython(create_treatments),
        migrations.RunPython(create_base_treatments),
        migrations.RunPython(create_menus_data),
        migrations.RunPython(create_meal_schedule),
    ]
