# Generated by Django 3.2.6 on 2021-08-28 21:18

from django.db import migrations

from diets.utils.seed import create_data


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
