# Generated by Django 3.2.6 on 2021-08-29 00:40

from django.db import migrations

from diets.utils.seed import create_data, create_meals_data


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
        migrations.RunPython(create_meals_data)
    ]
