# Generated by Django 3.2.6 on 2021-08-28 21:23

from django.db import migrations

from diets.utils.seed import create_meals_data


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_auto_20210828_1618'),
    ]

    operations = [
        migrations.RunPython(create_meals_data)
    ]
