# Generated by Django 3.2.6 on 2021-09-20 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_patientlog_date'),
        ('diseases', '0001_initial'),
        ('diets', '0002_auto_20210828_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('REFRESHMENT', 'Refreshment'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=50)),
            ],
            options={
                'db_table': 'meal_schedules',
            },
        ),
        migrations.CreateModel(
            name='PersonalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'personal_treatments',
            },
        ),
        migrations.CreateModel(
            name='PersonalTreatmentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('personal_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.personaltreatment')),
            ],
            options={
                'db_table': 'personal_treatment_traces',
            },
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='carbohydrate',
            new_name='carbohydrate_grams',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='fat',
            new_name='carbohydrate_kcal',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='protein',
            new_name='fat_grams',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='meal',
            name='fat_kcal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='protein_grams',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='protein_kcal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='illness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diseases.illness'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='protein',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='personaltreatment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.treatment'),
        ),
        migrations.AddField(
            model_name='mealschedule',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.meal'),
        ),
        migrations.AddField(
            model_name='mealschedule',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.menu'),
        ),
    ]
