# Generated by Django 3.2.6 on 2021-09-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_auto_20210923_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetreatment',
            name='years_old',
            field=models.CharField(max_length=4),
        ),
    ]
