# Generated by Django 3.2.6 on 2021-09-23 23:37

from django.db import migrations

from diets.utils.seed import create_treatments


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_alter_basetreatment_years_old'),
    ]

    operations = [
        migrations.RunPython(create_treatments)
    ]
