# Generated by Django 3.2.6 on 2021-09-23 23:58

from django.db import migrations

from diets.utils.seed import create_base_treatments


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_auto_20210923_1837'),
    ]

    operations = [
        migrations.RunPython(create_base_treatments)
    ]
