# Generated by Django 3.2.6 on 2021-09-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_auto_20210923_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealschedule',
            name='schedule',
            field=models.CharField(choices=[('BREAKFAST1', 'Breakfast1'), ('BREAKFAST2', 'Breakfast2'), ('SNACK', 'Snack'), ('LUNCH1', 'Lunch1'), ('LUNCH2', 'Lunch2'), ('LUNCH3', 'Lunch3'), ('DINNER1', 'Dinner1'), ('DINNER2', 'Dinner2')], max_length=50),
        ),
    ]
