# Generated by Django 3.2.6 on 2021-09-24 00:38

from django.db import migrations

from diets.utils.seed import create_menus_data, create_meal_schedule


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_alter_mealschedule_schedule'),
    ]

    operations = [
        migrations.RunPython(create_menus_data),
        migrations.RunPython(create_meal_schedule),
    ]
